### ISSUE TITLE
Bintray went off into the sunset / Secure Connection Failed

### ISSUE THREAD

**Issue by MaxPeal** [on-prem/tinycore-cloud-init#1]
Bintray went off into the sunset,
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

and also the links are dead e.g. 
```https://dl.bintray.com/on-prem/tinycore-extensions/11.0-x86_64/ifupdown/
Secure Connection Failed

An error occurred during a connection to dl.bintray.com. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

- Can we migrate it to Github Packages?
- or its is possible to add it to the official tinycore repro?

**Comment by aw** [comment]
Hi,

I never ended up deploying this to production so it's not currently in use.

If you need it, please feel free to make a pull request with the changes you want, and i'll be happy to review and accept if it's good.
